// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

import FirebaseFirestore
import Foundation

public enum ActivityCollection {
    public static let name = "activities"

    public static func documentPath(_ id: String) -> String {
        "activities/\(id)"
    }
}

public enum ActivityFields {
    public static let id = "id"
    public static let projectId = "projectId"
    public static let epicId = "epicId"
    public static let content = "content"
    public static let startedAt = "startedAt"
    public static let endedAt = "endedAt"
    public static let userId = "userId"
    public static let userName = "userName"
    public static let userIcon = "userIcon"
    public static let createdAt = "createdAt"
    public static let updatedAt = "updatedAt"
}

public struct Activity: Codable, Identifiable, Sendable {
    @DocumentID public var id: String?
    public var projectId: String
    public var epicId: String
    public var content: String
    public var startedAt: Date
    public var endedAt: Date
    public var userId: String
    public var userName: String
    public var userIcon: String
    @ServerTimestamp public var createdAt: Date?
    @ServerTimestamp public var updatedAt: Date?

    public init(
        projectId: String,
        epicId: String,
        content: String,
        startedAt: Date,
        endedAt: Date,
        userId: String,
        userName: String,
        userIcon: String
    ) {
        self.projectId = projectId
        self.epicId = epicId
        self.content = content
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.userId = userId
        self.userName = userName
        self.userIcon = userIcon
    }
}
