// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

import FirebaseFirestore
import Foundation

public enum DomainCollection {
    public static let name = "domains"

    public static func documentPath(_ id: String) -> String {
        "domains/\(id)"
    }
}

public enum DomainFields {
    public static let id = "id"
    public static let title = "title"
    public static let description = "description"
    public static let topics = "topics"
    public static let iconUrl = "iconUrl"
    public static let createdAt = "createdAt"
    public static let updatedAt = "updatedAt"
}

public struct Domain: Codable, Identifiable, Sendable {
    @DocumentID public var id: String?
    public var title: String
    public var description: String
    public var topics: [Topic]
    public var iconUrl: String?
    @ServerTimestamp public var createdAt: Date?
    @ServerTimestamp public var updatedAt: Date?

    public init(
        title: String,
        description: String,
        topics: [Topic] = [],
        iconUrl: String? = nil
    ) {
        self.title = title
        self.description = description
        self.topics = topics
        self.iconUrl = iconUrl
    }
}

public enum TopicFields {
    public static let id = "id"
    public static let title = "title"
    public static let imageUrl = "imageUrl"
}

public struct Topic: Codable, Identifiable, Sendable {
    public var id: String
    public var title: String
    public var imageUrl: String

    public init(
        id: String,
        title: String,
        imageUrl: String
    ) {
        self.id = id
        self.title = title
        self.imageUrl = imageUrl
    }
}
