// Code generated by youdoyou-firestore-kit. DO NOT EDIT.

import FirebaseFirestore
import Foundation

public enum ProjectCollection {
    public static let name = "projects"

    public static func documentPath(_ id: String) -> String {
        "projects/\(id)"
    }
}

public enum ProjectFields {
    public static let id = "id"
    public static let title = "title"
    public static let description = "description"
    public static let epics = "epics"
    public static let iconUrl = "iconUrl"
    public static let createdAt = "createdAt"
    public static let updatedAt = "updatedAt"
}

public struct Project: Codable, Identifiable, Sendable {
    @DocumentID public var id: String?
    public var title: String
    public var description: String
    public var epics: [Epic]
    public var iconUrl: String?
    @ServerTimestamp public var createdAt: Date?
    @ServerTimestamp public var updatedAt: Date?

    public init(
        title: String,
        description: String,
        epics: [Epic] = [],
        iconUrl: String? = nil
    ) {
        self.title = title
        self.description = description
        self.epics = epics
        self.iconUrl = iconUrl
    }
}

public enum EpicFields {
    public static let id = "id"
    public static let title = "title"
    public static let imageUrl = "imageUrl"
}

public struct Epic: Codable, Identifiable, Sendable {
    public var id: String
    public var title: String
    public var imageUrl: String

    public init(
        id: String,
        title: String,
        imageUrl: String
    ) {
        self.id = id
        self.title = title
        self.imageUrl = imageUrl
    }
}
